name = "llm-compare"
main = ".open-next/worker.js"
compatibility_date = "2025-11-01"
compatibility_flags = ["nodejs_compat"]

[assets]
directory = "./.open-next/assets"

[[d1_databases]]
binding = "DB"
database_name = "llm-compare-db"
database_id = "33345f08-ec70-40e2-a592-adb6a9c33a92"
